// Generated by @xz-lang/bridge. Do not edit.
import { loadLibrary, type FfiBackend, type LibraryManifest } from "@xz-lang/bridge";

export interface LineItem {
  quantity: number;
  unit_price: number;
}

export const manifest: LibraryManifest = {
  name: "order",
  path: ".next-xz/liborder.so",
  xzVersion: "0.1.0",
  symbols: {
    "line_total": { args: [{ kind: "struct", name: "LineItem", fields: [{ name: "quantity", type: "int64" }, { name: "unit_price", type: "double" }] }], returns: "double" },
    "payable_total": { args: ["double", "double"], returns: "double" },
  },
};

export interface Binding {
  line_total(item: LineItem): number;
  payable_total(subtotal: number, tax_rate: number): number;
  close(): void;
}

export function bind(backend: FfiBackend): Binding {
  const loaded = loadLibrary(manifest, { expectedXzVersion: manifest.xzVersion, backend });
  const symbols = loaded.symbols as Readonly<Record<string, (...args: unknown[]) => unknown>>;
  return {
    line_total(item) {
      return symbols["line_total"]!(item) as number;
    },
    payable_total(subtotal, tax_rate) {
      return symbols["payable_total"]!(subtotal, tax_rate) as number;
    },
    close: () => {
      loaded.close();
    },
  };
}
