// Generated by @xz-lang/bridge. Do not edit.
import { loadLibrary, loadPlatformLibrary, asXzInt, type FfiBackend, type LibraryManifest, type LoadedLibrary } from "@xz-lang/bridge";

export interface LineItem {
  quantity: bigint;
  unit_price: number;
}

export const manifest: LibraryManifest = {
  name: "order",
  path: ".next-xz/liborder.so",
  xzVersion: "0.1.0",
  symbols: {
    "line_total": { args: [{ kind: "struct", name: "LineItem", fields: [{ name: "quantity", type: "int64" }, { name: "unit_price", type: "double" }] }], returns: "double" },
    "payable_total": { args: ["double", "double"], returns: "double" },
  },
};

function normalizeLineItem(value: LineItem): LineItem {
  return {
    ...value,
    quantity: asXzInt(value.quantity),
  };
}

export interface Binding {
  line_total(item: LineItem): number;
  payable_total(subtotal: number, tax_rate: number): number;
  close(): void;
}

export function bind(backend: FfiBackend): Binding {
  return createBinding(
    loadLibrary(manifest, { expectedXzVersion: manifest.xzVersion, backend }),
  );
}

export async function loadPlatform(): Promise<Binding> {
  return createBinding(
    await loadPlatformLibrary(manifest, { expectedXzVersion: manifest.xzVersion }),
  );
}

function createBinding(loaded: LoadedLibrary): Binding {
  const symbols = loaded.symbols as Readonly<Record<string, (...args: unknown[]) => unknown>>;
  return {
    line_total(item) {
      return symbols["line_total"]!(normalizeLineItem(item)) as number;
    },
    payable_total(subtotal, tax_rate) {
      return symbols["payable_total"]!(subtotal, tax_rate) as number;
    },
    close: () => {
      loaded.close();
    },
  };
}
