import { BridgeDefinitionError } from "./errors.js";
import { manifestFromInterface, type LibraryManifest } from "./ffi/manifest.js";
import type { FfiType } from "./ffi/types.js";
import { cstructNames, mapTypeToTs, renderXzType } from "./type-map.js";
import type { CStruct, ExternFunc, Interface, Param, XzType } from "./xzint/ast.js";

export interface GenerateOptions {
  readonly name: string;
  readonly libraryPath: string;
  readonly xzVersion: string;
  readonly importFrom?: string;
}

const DEFAULT_IMPORT = "@xz-lang/bridge";

export function generateBinding(iface: Interface, options: GenerateOptions): string {
  const manifest = manifestFromInterface(iface, {
    name: options.name,
    path: options.libraryPath,
    xzVersion: options.xzVersion,
  });
  const cstructs: ReadonlyMap<string, CStruct> = new Map(
    iface.cstructs.map((cstruct) => [cstruct.name, cstruct]),
  );
  const names = cstructNames(iface);

  for (const func of iface.funcs) {
    assertGeneratable(func, cstructs, iface.kind === "foreign");
  }

  const needs = collectMarshalling(iface);

  const lines: string[] = [];
  lines.push("// Generated by @xz-lang/bridge. Do not edit.");
  lines.push(emitImport(needs, options.importFrom ?? DEFAULT_IMPORT));
  lines.push("");

  for (const cstruct of iface.cstructs) {
    lines.push(...emitCStruct(cstruct, names));
    lines.push("");
  }

  lines.push(...emitManifest(manifest));
  lines.push("");
  lines.push(...emitBindingInterface(iface, names));
  lines.push("");
  lines.push(...emitBindFunction(iface, names, needs));
  lines.push("");
  return lines.join("\n");
}

function assertGeneratable(
  func: ExternFunc,
  cstructs: ReadonlyMap<string, CStruct>,
  foreign: boolean,
): void {
  if (func.transferReturn) {
    if (!foreign) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': a 'transfer' return is legal only on an '@interface foreign'; an Xz '@export' surface retains its returns`,
      );
    }
    if (!isNamed(func.returnType, "Str") && !isNamed(func.returnType, "Bytes")) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': a 'transfer' return is emitted only for top-level Str/Bytes; '${renderXzType(func.returnType)}' has no release path`,
      );
    }
    if (func.release === undefined) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': a 'transfer' return must declare its deallocator with 'release <symbol>'`,
      );
    }
  }
  for (const param of func.params) {
    if (param.transfer) {
      if (!foreign) {
        throw new BridgeDefinitionError(
          `symbol '${func.name}': a 'transfer' parameter is legal only on an '@interface foreign'; Xz forbids ownership transfer on '@export'`,
        );
      }
      if (!isNamed(param.type, "Str") && !isNamed(param.type, "Bytes")) {
        throw new BridgeDefinitionError(
          `symbol '${func.name}': parameter '${param.name}' is declared 'transfer'; ownership handoff is emitted only for top-level Str and Bytes buffers, which the binding can retain`,
        );
      }
    }
    if (param.mutable) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': mutable parameter '${param.name}' has no generated binding yet; the contract wrapper pattern (docs/01 section 5) is not emitted from .xzint`,
      );
    }
    assertMarshallable(func.name, param.type, cstructs, "param");
  }
  assertMarshallable(func.name, func.returnType, cstructs, "return");
}

function assertMarshallable(
  symbol: string,
  type: XzType,
  cstructs: ReadonlyMap<string, CStruct>,
  position: "param" | "return" | "field",
): void {
  if (type.kind === "named" && (type.name === "Str" || type.name === "Bytes")) {
    if (position === "field") {
      throw new BridgeDefinitionError(
        `symbol '${symbol}': '${type.name}' as a @cstruct field is not marshalled by the generated binding; pass it as a top-level parameter or return instead`,
      );
    }
    return;
  }
  if (type.kind === "named" && cstructs.has(type.name)) {
    for (const field of cstructs.get(type.name)!.fields) {
      assertMarshallable(symbol, field.type, cstructs, "field");
    }
  }
}

function emitCStruct(cstruct: CStruct, names: ReadonlySet<string>): string[] {
  const lines = [`export interface ${cstruct.name} {`];
  for (const field of cstruct.fields) {
    lines.push(`  ${field.name}: ${mapTypeToTs(field.type, names, "field")};`);
  }
  lines.push("}");
  return lines;
}

function emitManifest(manifest: LibraryManifest): string[] {
  const lines = ["export const manifest: LibraryManifest = {"];
  lines.push(`  name: ${JSON.stringify(manifest.name)},`);
  lines.push(`  path: ${JSON.stringify(manifest.path)},`);
  lines.push(`  xzVersion: ${JSON.stringify(manifest.xzVersion)},`);
  lines.push("  symbols: {");
  for (const [name, definition] of Object.entries(manifest.symbols)) {
    const args = definition.args.map(emitFfiType).join(", ");
    const release =
      definition.release === undefined ? "" : `, release: ${JSON.stringify(definition.release)}`;
    lines.push(
      `    ${JSON.stringify(name)}: { args: [${args}], returns: ${emitFfiType(definition.returns)}${release} },`,
    );
  }
  lines.push("  },");
  lines.push("};");
  return lines;
}

function emitFfiType(type: FfiType): string {
  if (typeof type === "string") {
    return JSON.stringify(type);
  }
  const fields = type.fields
    .map((field) => `{ name: ${JSON.stringify(field.name)}, type: ${emitFfiType(field.type)} }`)
    .join(", ");
  return `{ kind: "struct", name: ${JSON.stringify(type.name)}, fields: [${fields}] }`;
}

function emitBindingInterface(iface: Interface, names: ReadonlySet<string>): string[] {
  const lines = ["export interface Binding {"];
  for (const func of iface.funcs) {
    const params = func.params
      .map((param) => `${param.name}: ${mapTypeToTs(param.type, names, "param")}`)
      .join(", ");
    lines.push(`  ${func.name}(${params}): ${mapTypeToTs(func.returnType, names, "return")};`);
  }
  lines.push("  close(): void;");
  lines.push("}");
  return lines;
}

interface MarshallingNeeds {
  encodeStr: boolean;
  encodeBytes: boolean;
  decodeStr: boolean;
  decodeBytes: boolean;
  pointerValue: boolean;
  asXzInt: boolean;
  retention: boolean;
}

function collectMarshalling(iface: Interface): MarshallingNeeds {
  const needs: MarshallingNeeds = {
    encodeStr: false,
    encodeBytes: false,
    decodeStr: false,
    decodeBytes: false,
    pointerValue: false,
    asXzInt: false,
    retention: false,
  };
  for (const func of iface.funcs) {
    for (const param of func.params) {
      if (isNamed(param.type, "Str")) needs.encodeStr = true;
      if (isNamed(param.type, "Bytes")) needs.encodeBytes = true;
      if (param.transfer) needs.retention = true;
      if (isIntType(param.type)) needs.asXzInt = true;
    }
    if (isNamed(func.returnType, "Str")) {
      needs.decodeStr = true;
      needs.pointerValue = true;
    }
    if (isNamed(func.returnType, "Bytes")) {
      needs.decodeBytes = true;
      needs.pointerValue = true;
    }
    if (isIntType(func.returnType)) needs.asXzInt = true;
  }
  return needs;
}

function isNamed(type: XzType, name: string): boolean {
  return type.kind === "named" && type.name === name;
}

function isIntType(type: XzType): boolean {
  return isNamed(type, "Int") || isNamed(type, "usize");
}

function emitImport(needs: MarshallingNeeds, module: string): string {
  const values = ["loadLibrary", "loadPlatformLibrary"];
  if (needs.encodeStr) values.push("encodeStr");
  if (needs.encodeBytes) values.push("encodeBytes");
  if (needs.decodeStr) values.push("decodeStr");
  if (needs.decodeBytes) values.push("decodeBytes");
  if (needs.asXzInt) values.push("asXzInt");
  const types = ["type FfiBackend", "type LibraryManifest", "type LoadedLibrary"];
  if (needs.pointerValue) types.push("type XzPointerValue");
  return `import { ${[...values, ...types].join(", ")} } from ${JSON.stringify(module)};`;
}

function emitBindFunction(
  iface: Interface,
  names: ReadonlySet<string>,
  needs: MarshallingNeeds,
): string[] {
  const lines = ["export function bind(backend: FfiBackend): Binding {"];
  lines.push("  return createBinding(");
  lines.push("    loadLibrary(manifest, { expectedXzVersion: manifest.xzVersion, backend }),");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("export async function loadPlatform(): Promise<Binding> {");
  lines.push("  return createBinding(");
  lines.push("    await loadPlatformLibrary(manifest, { expectedXzVersion: manifest.xzVersion }),");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("function createBinding(loaded: LoadedLibrary): Binding {");
  lines.push(
    "  const symbols = loaded.symbols as Readonly<Record<string, (...args: unknown[]) => unknown>>;",
  );
  if (needs.retention) {
    lines.push("  const retained: Uint8Array[] = [];");
  }
  lines.push("  return {");
  for (const func of iface.funcs) {
    const params = func.params.map((param) => param.name).join(", ");
    const preamble: string[] = [];
    const args = func.params.map((param) => emitArgument(param, preamble));
    const call = `symbols[${JSON.stringify(func.name)}]!(${args.join(", ")})`;
    lines.push(`    ${func.name}(${params}) {`);
    for (const line of preamble) {
      lines.push(`      ${line}`);
    }
    if (
      func.transferReturn &&
      (isNamed(func.returnType, "Str") || isNamed(func.returnType, "Bytes"))
    ) {
      const decode = isNamed(func.returnType, "Str") ? "decodeStr" : "decodeBytes";
      lines.push(`      const result = ${call} as XzPointerValue;`);
      lines.push("      try {");
      lines.push(`        return ${decode}(result);`);
      lines.push("      } finally {");
      lines.push(`        symbols[${JSON.stringify(func.release!)}]!(result.address ?? result.ptr);`);
      lines.push("      }");
    } else if (isNamed(func.returnType, "Str")) {
      lines.push(`      return decodeStr(${call} as XzPointerValue);`);
    } else if (isNamed(func.returnType, "Bytes")) {
      lines.push(`      return decodeBytes(${call} as XzPointerValue);`);
    } else if (isNamed(func.returnType, "Unit")) {
      lines.push(`      ${call};`);
    } else if (isIntType(func.returnType)) {
      lines.push(`      return asXzInt(${call});`);
    } else {
      const returnTs = mapTypeToTs(func.returnType, names, "return");
      lines.push(`      return ${call} as ${returnTs};`);
    }
    lines.push("    },");
  }
lines.push("    close: () => {");
    if (needs.retention) {
      lines.push("      retained.length = 0;");
    }
    lines.push("      loaded.close();");
    lines.push("    },");
    lines.push("  };");
    lines.push("}");
    return lines;
}

function emitArgument(param: Param, preamble: string[]): string {
  if (isNamed(param.type, "Str")) {
    if (param.transfer) {
      preamble.push(`const ${param.name}Pointer = encodeStr(${param.name});`);
      preamble.push(`retained.push(${param.name}Pointer.ptr);`);
      return `${param.name}Pointer`;
    }
    return `encodeStr(${param.name})`;
  }
  if (isNamed(param.type, "Bytes")) {
    if (param.transfer) {
      preamble.push(`const ${param.name}Pointer = encodeBytes(${param.name});`);
      preamble.push(`retained.push(${param.name}Pointer.ptr);`);
      return `${param.name}Pointer`;
    }
    return `encodeBytes(${param.name})`;
  }
  if (isIntType(param.type)) {
    return `asXzInt(${param.name})`;
  }
  return param.name;
}