import { BridgeDefinitionError } from "./errors.js";
import { manifestFromInterface, type LibraryManifest } from "./ffi/manifest.js";
import type { FfiType } from "./ffi/types.js";
import { cstructNames, mapTypeToTs } from "./type-map.js";
import type { CStruct, ExternFunc, Interface, Param, XzType } from "./xzint/ast.js";

export interface GenerateOptions {
  readonly name: string;
  readonly libraryPath: string;
  readonly xzVersion: string;
  readonly importFrom?: string;
}

const DEFAULT_IMPORT = "@xz-lang/bridge";

export function generateBinding(iface: Interface, options: GenerateOptions): string {
  const manifest = manifestFromInterface(iface, {
    name: options.name,
    path: options.libraryPath,
    xzVersion: options.xzVersion,
  });
  const cstructs: ReadonlyMap<string, CStruct> = new Map(
    iface.cstructs.map((cstruct) => [cstruct.name, cstruct]),
  );
  const names = cstructNames(iface);

  for (const func of iface.funcs) {
    assertGeneratable(func, cstructs);
  }

  const needs = collectMarshalling(iface);

  const lines: string[] = [];
  lines.push("// Generated by @xz-lang/bridge. Do not edit.");
  lines.push(emitImport(needs, options.importFrom ?? DEFAULT_IMPORT));
  lines.push("");

  for (const cstruct of iface.cstructs) {
    lines.push(...emitCStruct(cstruct, names));
    lines.push("");
  }

  lines.push(...emitManifest(manifest));
  lines.push("");
  lines.push(...emitBindingInterface(iface, names));
  lines.push("");
  lines.push(...emitBindFunction(iface, names));
  lines.push("");
  return lines.join("\n");
}

function assertGeneratable(
  func: ExternFunc,
  cstructs: ReadonlyMap<string, CStruct>,
): void {
  if (func.transferReturn) {
    throw new BridgeDefinitionError(
      `symbol '${func.name}': return is declared 'transfer'; the generated binding copies the returned buffer and cannot take ownership of it`,
    );
  }
  for (const param of func.params) {
    if (param.mutable) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': mutable parameter '${param.name}' has no generated binding yet; the contract wrapper pattern (docs/01 section 5) is not emitted from .xzint`,
      );
    }
    assertMarshallable(func.name, param.type, cstructs, "param");
  }
  assertMarshallable(func.name, func.returnType, cstructs, "return");
}

function assertMarshallable(
  symbol: string,
  type: XzType,
  cstructs: ReadonlyMap<string, CStruct>,
  position: "param" | "return" | "field",
): void {
  if (type.kind === "named" && (type.name === "Str" || type.name === "Bytes")) {
    if (position === "field") {
      throw new BridgeDefinitionError(
        `symbol '${symbol}': '${type.name}' as a @cstruct field is not marshalled by the generated binding; pass it as a top-level parameter or return instead`,
      );
    }
    return;
  }
  if (type.kind === "named" && cstructs.has(type.name)) {
    for (const field of cstructs.get(type.name)!.fields) {
      assertMarshallable(symbol, field.type, cstructs, "field");
    }
  }
}

function emitCStruct(cstruct: CStruct, names: ReadonlySet<string>): string[] {
  const lines = [`export interface ${cstruct.name} {`];
  for (const field of cstruct.fields) {
    lines.push(`  ${field.name}: ${mapTypeToTs(field.type, names, "field")};`);
  }
  lines.push("}");
  return lines;
}

function emitManifest(manifest: LibraryManifest): string[] {
  const lines = ["export const manifest: LibraryManifest = {"];
  lines.push(`  name: ${JSON.stringify(manifest.name)},`);
  lines.push(`  path: ${JSON.stringify(manifest.path)},`);
  lines.push(`  xzVersion: ${JSON.stringify(manifest.xzVersion)},`);
  lines.push("  symbols: {");
  for (const [name, definition] of Object.entries(manifest.symbols)) {
    const args = definition.args.map(emitFfiType).join(", ");
    lines.push(
      `    ${JSON.stringify(name)}: { args: [${args}], returns: ${emitFfiType(definition.returns)} },`,
    );
  }
  lines.push("  },");
  lines.push("};");
  return lines;
}

function emitFfiType(type: FfiType): string {
  if (typeof type === "string") {
    return JSON.stringify(type);
  }
  const fields = type.fields
    .map((field) => `{ name: ${JSON.stringify(field.name)}, type: ${emitFfiType(field.type)} }`)
    .join(", ");
  return `{ kind: "struct", name: ${JSON.stringify(type.name)}, fields: [${fields}] }`;
}

function emitBindingInterface(iface: Interface, names: ReadonlySet<string>): string[] {
  const lines = ["export interface Binding {"];
  for (const func of iface.funcs) {
    const params = func.params
      .map((param) => `${param.name}: ${mapTypeToTs(param.type, names, "param")}`)
      .join(", ");
    lines.push(`  ${func.name}(${params}): ${mapTypeToTs(func.returnType, names, "return")};`);
  }
  lines.push("  close(): void;");
  lines.push("}");
  return lines;
}

interface MarshallingNeeds {
  encodeStr: boolean;
  encodeBytes: boolean;
  decodeStr: boolean;
  decodeBytes: boolean;
  pointerValue: boolean;
}

function collectMarshalling(iface: Interface): MarshallingNeeds {
  const needs: MarshallingNeeds = {
    encodeStr: false,
    encodeBytes: false,
    decodeStr: false,
    decodeBytes: false,
    pointerValue: false,
  };
  for (const func of iface.funcs) {
    for (const param of func.params) {
      if (isNamed(param.type, "Str")) needs.encodeStr = true;
      if (isNamed(param.type, "Bytes")) needs.encodeBytes = true;
    }
    if (isNamed(func.returnType, "Str")) {
      needs.decodeStr = true;
      needs.pointerValue = true;
    }
    if (isNamed(func.returnType, "Bytes")) {
      needs.decodeBytes = true;
      needs.pointerValue = true;
    }
  }
  return needs;
}

function isNamed(type: XzType, name: string): boolean {
  return type.kind === "named" && type.name === name;
}

function emitImport(needs: MarshallingNeeds, module: string): string {
  const values = ["loadLibrary", "loadPlatformLibrary"];
  if (needs.encodeStr) values.push("encodeStr");
  if (needs.encodeBytes) values.push("encodeBytes");
  if (needs.decodeStr) values.push("decodeStr");
  if (needs.decodeBytes) values.push("decodeBytes");
  const types = ["type FfiBackend", "type LibraryManifest", "type LoadedLibrary"];
  if (needs.pointerValue) types.push("type XzPointerValue");
  return `import { ${[...values, ...types].join(", ")} } from ${JSON.stringify(module)};`;
}

function emitBindFunction(iface: Interface, names: ReadonlySet<string>): string[] {
  const lines = ["export function bind(backend: FfiBackend): Binding {"];
  lines.push("  return createBinding(");
  lines.push("    loadLibrary(manifest, { expectedXzVersion: manifest.xzVersion, backend }),");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("export async function loadPlatform(): Promise<Binding> {");
  lines.push("  return createBinding(");
  lines.push("    await loadPlatformLibrary(manifest, { expectedXzVersion: manifest.xzVersion }),");
  lines.push("  );");
  lines.push("}");
  lines.push("");
  lines.push("function createBinding(loaded: LoadedLibrary): Binding {");
  lines.push(
    "  const symbols = loaded.symbols as Readonly<Record<string, (...args: unknown[]) => unknown>>;",
  );
  lines.push("  return {");
  for (const func of iface.funcs) {
    const params = func.params.map((param) => param.name).join(", ");
    const args = func.params.map(emitArgument);
    const call = `symbols[${JSON.stringify(func.name)}]!(${args.join(", ")})`;
    lines.push(`    ${func.name}(${params}) {`);
    if (isNamed(func.returnType, "Str")) {
      lines.push(`      return decodeStr(${call} as XzPointerValue);`);
    } else if (isNamed(func.returnType, "Bytes")) {
      lines.push(`      return decodeBytes(${call} as XzPointerValue);`);
    } else if (isNamed(func.returnType, "Unit")) {
      lines.push(`      ${call};`);
    } else {
      const returnTs = mapTypeToTs(func.returnType, names, "return");
      lines.push(`      return ${call} as ${returnTs};`);
    }
    lines.push("    },");
  }
  lines.push("    close: () => {");
  lines.push("      loaded.close();");
  lines.push("    },");
  lines.push("  };");
  lines.push("}");
  return lines;
}

function emitArgument(param: Param): string {
  if (isNamed(param.type, "Str")) {
    return `encodeStr(${param.name})`;
  }
  if (isNamed(param.type, "Bytes")) {
    return `encodeBytes(${param.name})`;
  }
  return param.name;
}