import { BridgeDefinitionError } from "./errors.js";
import { manifestFromInterface, type LibraryManifest } from "./ffi/manifest.js";
import type { FfiType } from "./ffi/types.js";
import { cstructNames, isPrimitive, mapTypeToTs } from "./type-map.js";
import type { CStruct, ExternFunc, Interface, XzType } from "./xzint/ast.js";

export interface GenerateOptions {
  readonly name: string;
  readonly libraryPath: string;
  readonly xzVersion: string;
  readonly importFrom?: string;
}

const DEFAULT_IMPORT = "@xz-lang/bridge";

export function generateBinding(iface: Interface, options: GenerateOptions): string {
  const cstructs: ReadonlyMap<string, CStruct> = new Map(
    iface.cstructs.map((cstruct) => [cstruct.name, cstruct]),
  );
  const names = cstructNames(iface);

  for (const func of iface.funcs) {
    assertGeneratable(func, cstructs, names);
  }

  const manifest = manifestFromInterface(iface, {
    name: options.name,
    path: options.libraryPath,
    xzVersion: options.xzVersion,
  });

  const lines: string[] = [];
  lines.push("// Generated by @xz-lang/bridge. Do not edit.");
  lines.push(
    `import { loadLibrary, type FfiBackend, type LibraryManifest } from ${JSON.stringify(
      options.importFrom ?? DEFAULT_IMPORT,
    )};`,
  );
  lines.push("");

  for (const cstruct of iface.cstructs) {
    lines.push(...emitCStruct(cstruct, names));
    lines.push("");
  }

  lines.push(...emitManifest(manifest));
  lines.push("");
  lines.push(...emitBindingInterface(iface, names));
  lines.push("");
  lines.push(...emitBindFunction(iface, names));
  lines.push("");
  return lines.join("\n");
}

function assertGeneratable(
  func: ExternFunc,
  cstructs: ReadonlyMap<string, CStruct>,
  names: ReadonlySet<string>,
): void {
  for (const param of func.params) {
    if (param.transfer) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': parameter '${param.name}' is declared 'transfer'; the generated binding borrows buffers for the call only and cannot hand off ownership (docs/01 section 4.2)`,
      );
    }
    if (param.mutable) {
      throw new BridgeDefinitionError(
        `symbol '${func.name}': mutable parameter '${param.name}' has no generated binding yet; the contract wrapper pattern (docs/01 section 5) is not emitted from .xzint`,
      );
    }
    assertMarshallable(func.name, param.type, cstructs, names, "param");
  }
  assertMarshallable(func.name, func.returnType, cstructs, names, "return");
}

function assertMarshallable(
  symbol: string,
  type: XzType,
  cstructs: ReadonlyMap<string, CStruct>,
  names: ReadonlySet<string>,
  position: "param" | "return",
): void {
  if (type.kind === "generic") {
    throw new BridgeDefinitionError(
      `symbol '${symbol}': generic type '${type.name}' is not C-representable`,
    );
  }
  if (type.name === "Str" || type.name === "Bytes") {
    throw new BridgeDefinitionError(
      `symbol '${symbol}': '${type.name}' needs encode/decode marshalling, which the generated binding does not emit yet`,
    );
  }
  if (isPrimitive(type.name)) {
    if (type.name === "Unit" && position === "param") {
      throw new BridgeDefinitionError(`symbol '${symbol}': Unit is allowed only as a return type`);
    }
    return;
  }
  const record = cstructs.get(type.name);
  if (record === undefined) {
    throw new BridgeDefinitionError(
      `symbol '${symbol}': unknown type '${type.name}'; declare it as a @cstruct record`,
    );
  }
  for (const field of record.fields) {
    assertMarshallable(symbol, field.type, cstructs, names, "param");
  }
}

function emitCStruct(cstruct: CStruct, names: ReadonlySet<string>): string[] {
  const lines = [`export interface ${cstruct.name} {`];
  for (const field of cstruct.fields) {
    lines.push(`  ${field.name}: ${mapTypeToTs(field.type, names, "field")};`);
  }
  lines.push("}");
  return lines;
}

function emitManifest(manifest: LibraryManifest): string[] {
  const lines = ["export const manifest: LibraryManifest = {"];
  lines.push(`  name: ${JSON.stringify(manifest.name)},`);
  lines.push(`  path: ${JSON.stringify(manifest.path)},`);
  lines.push(`  xzVersion: ${JSON.stringify(manifest.xzVersion)},`);
  lines.push("  symbols: {");
  for (const [name, definition] of Object.entries(manifest.symbols)) {
    const args = definition.args.map(emitFfiType).join(", ");
    lines.push(
      `    ${JSON.stringify(name)}: { args: [${args}], returns: ${emitFfiType(definition.returns)} },`,
    );
  }
  lines.push("  },");
  lines.push("};");
  return lines;
}

function emitFfiType(type: FfiType): string {
  if (typeof type === "string") {
    return JSON.stringify(type);
  }
  const fields = type.fields
    .map((field) => `{ name: ${JSON.stringify(field.name)}, type: ${emitFfiType(field.type)} }`)
    .join(", ");
  return `{ kind: "struct", name: ${JSON.stringify(type.name)}, fields: [${fields}] }`;
}

function emitBindingInterface(iface: Interface, names: ReadonlySet<string>): string[] {
  const lines = ["export interface Binding {"];
  for (const func of iface.funcs) {
    const params = func.params
      .map((param) => `${param.name}: ${mapTypeToTs(param.type, names, "param")}`)
      .join(", ");
    lines.push(`  ${func.name}(${params}): ${mapTypeToTs(func.returnType, names, "return")};`);
  }
  lines.push("  close(): void;");
  lines.push("}");
  return lines;
}

function emitBindFunction(iface: Interface, names: ReadonlySet<string>): string[] {
  const lines = ["export function bind(backend: FfiBackend): Binding {"];
  lines.push(
    "  const loaded = loadLibrary(manifest, { expectedXzVersion: manifest.xzVersion, backend });",
  );
  lines.push(
    "  const symbols = loaded.symbols as Readonly<Record<string, (...args: unknown[]) => unknown>>;",
  );
  lines.push("  return {");
  for (const func of iface.funcs) {
    const params = func.params.map((param) => param.name).join(", ");
    const call = `symbols[${JSON.stringify(func.name)}]!(${params})`;
    if (func.returnType.kind === "named" && func.returnType.name === "Unit") {
      lines.push(`    ${func.name}(${params}): void {`);
      lines.push(`      ${call};`);
      lines.push("    },");
    } else {
      const returnTs = mapTypeToTs(func.returnType, names, "return");
      lines.push(`    ${func.name}(${params}) {`);
      lines.push(`      return ${call} as ${returnTs};`);
      lines.push("    },");
    }
  }
  lines.push("    close: () => loaded.close(),");
  lines.push("  };");
  lines.push("}");
  return lines;
}